server:
  port: 8005


# redis配置
spring:
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:

# dev环境开启mybatis日志
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 设置域名,在java代码中获取,这里是资源配置
website:
  domain-name: zxl.com

